Flag = -Wall -Wextra -Werror -pedantic

pc8: pc8.cpp
	g++ $(Flag) -o pc8 pc8.cpp

pc9: pc9.cpp
	g++ $(Flag) -o pc9 pc9.cpp

pc10: pc10.cpp
	g++ $(Flag) -o pc10 pc10.cpp

pc11: pc11.cpp
	g++ $(Flag) -o pc11 pc11.cpp

pc12: pc12.cpp
	g++ $(Flag) -o pc12 pc12.cpp

pc13:pc13.cpp
	g++ $(Flag) -o pc13 pc13.cpp

pc14:pc14.cpp
	g++ $(Flag) -o pc14 pc14.cpp
	
pc15:pc15.cpp
	g++ $(Flag) -o pc15 pc15.cpp
	
clean:
	rm *.o