Flag = -Wall -Wextra -Werror -pedantic

pc13: pc13.cpp
	g++ $(Flag) pc13.cpp -o pc13

pc14: pc14.cpp
	g++ $(Flag) pc14.cpp -o pc14

pc15: pc15.cpp
	g++ $(Flag) pc15.cpp -o pc15

pc16: pc16.cpp
	g++ $(Flag) pc16.cpp -o pc16